### ISSUE TITLE
Peer Review 7-25 

### ISSUE THREAD

**Issue by TartarSauce** [dougachrist/portfolio#11]
1. For each item that shows up on portfolio page, it will be nice to have the same number of words show up in each item before the "Read-more" tag.
2. On the admin page, remove the "Read-more" tag.
3. On the admin page, it will be nice if you enable the linking to other pages from the navbar. 
4. On the contact page, a submit button will complete the screen.

**Comment by dougachrist** [comment]
Thanks Uma,
1. read more tag is updated to cut off where I determine.
2. Read more is removed from Admin page.
3. link on Admin page now work (all one page)
4. button added to contact page.

Thanks for your help today.
