### ISSUE TITLE
corey-peer review

### ISSUE THREAD

**Issue by coreymalek** [dougachrist/portfolio#12]
- The organization of all of your files is immaculate. 
- One minor inconsistency that I noticed was that when you click from 'Home' to 'Projects', the background image and background color where the content is displayed remain constant. And when you click from 'Home' to the 'Bio' or 'Contact' tabs, the background image and color change. However, when you click back to 'Projects' from 'Bio' or 'Contact' (where the color and image have changed), the background image and color on 'Projects' then change to those same styles, only reverting back to it's original style if you navigate back to 'Home' then to 'Projects' again .. Is this something that you intended?
- In mobile view, why does that Starfish image only appear when the hamburger menu is activated? 
- In the 'Projects' tab, the content is reloaded and displayed on the page numerous times. I'm providing you with a link to check out to see if this method can help you with that :) 

http://stackoverflow.com/questions/21470982/backbonejs-handlebarsjs-how-to-avoid-html-to-be-rendered-multiple-times

**Comment by dougachrist** [comment]
Thank Corey - I updated the multiple blog postings, I'll keep working on the starfish and the background images, still not sure how I want this too look yet.
